apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 910704919207.dkr.ecr.us-west-2.amazonaws.com/udacity-capstone/backend:cd44c11
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: lb-services
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
