Description: >
    Ignacio Hidalgo / Udacity

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
    ClusterUdacity:
        Type: AWS::EKS::Cluster
        DependsOn: EKSSSGBase
        Properties:
            Name: !Sub ${EnvironmentName}-EKS
            RoleArn: !GetAtt EKSServiceRole.Arn
            Version: "1.14"
            ResourcesVpcConfig:
                SecurityGroupIds:
                    - !Ref EKSSSGBase
                SubnetIds:
                    - Fn::ImportValue: !Sub ${EnvironmentName}-PRI1-SN
                    - Fn::ImportValue: !Sub ${EnvironmentName}-PRI2-SN
                    - Fn::ImportValue: !Sub ${EnvironmentName}-PRI3-SN

    EKSNodegroup:
        Type: AWS::EKS::Nodegroup
        Properties:
            ClusterName: !Sub ${EnvironmentName}-EKS
            NodeRole: !GetAtt EKSInstanceRole.Arn
            ScalingConfig:
                MinSize: 3
                DesiredSize: 3
                MaxSize: 3
            Subnets:
                - Fn::ImportValue: !Sub ${EnvironmentName}-PRI1-SN
                - Fn::ImportValue: !Sub ${EnvironmentName}-PRI2-SN
                - Fn::ImportValue: !Sub ${EnvironmentName}-PRI3-SN

    EKSServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - eks.amazonaws.com
                      Action:
                          - sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
                - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

    EKSInstanceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - ec2.amazonaws.com
                      Action:
                          - sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
                - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
                - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

    EKSSSGBase:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Base Security Group EKS
            GroupName: !Sub ${EnvironmentName}-EKS
            VpcId:
                Fn::ImportValue: !Sub ${EnvironmentName}-VPCID

    EKSSSGBaseIngress:
        Type: AWS::EC2::SecurityGroupIngress
        DependsOn: EKSSSGBase
        Properties:
            GroupId: !GetAtt EKSSSGBase.GroupId
            IpProtocol: tcp
            FromPort: 0
            ToPort: 65535
            SourceSecurityGroupId: !GetAtt EKSSSGBase.GroupId

    EKSSSGBaseEgress:
        Type: AWS::EC2::SecurityGroupEgress
        DependsOn: EKSSSGBase
        Properties:
            GroupId: !GetAtt EKSSSGBase.GroupId
            IpProtocol: tcp
            FromPort: 0
            ToPort: 65535
            CidrIp: 0.0.0.0/0
